// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace insideAirbnb.Shared
{
    public partial class Availability
    {
        public int Month { get; set; }
        public int Available { get; set; }
        public int Total { get; set; }
    }
}