// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace insideAirbnb.Shared
{
    public partial class FilterParameters
    {
        public string Neighbourhood { get; set; }
    }
}