// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace insideAirbnb.Shared
{
    public partial class Geo
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string HostName { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public string Price { get; set; }
        public string Neighbourhood { get; set; }
        public int NumberOfReviews { get; set; }
    }
}