// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace insideAirbnb.Server
{
    public partial class Neighbourhoods
    {
        public string NeighbourhoodGroup { get; set; }
        public string Neighbourhood { get; set; }
    }
}