// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace insideAirbnb.Server
{
    public partial class Reviews
    {
        public int ListingId { get; set; }
        public DateTime Date { get; set; }
    }
}